services:

  api:
    build: .
    container_name: facial_api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/facial_db
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app

  db:
    image: postgres:17
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: facial_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d facial_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: